# Build stage
FROM alpine:3.20 AS builder

RUN apk add --no-cache \
    cmake \
    make \
    gcc \
    musl-dev \
    libusb-dev \
    pkgconfig \
    git

ARG VERSION

RUN git clone https://github.com/gbozo/rtl-sdr.git /src \
    --depth=1 --branch "${VERSION}"

RUN cmake -S /src -B /build \
        -DCMAKE_INSTALL_PREFIX=/install \
        -DCMAKE_BUILD_TYPE=Release \
    && cmake --build /build --parallel "$(nproc)" \
    && cmake --install /build

# Runtime stage
FROM alpine:3.20

RUN apk add --no-cache libusb

COPY --from=builder /install/ /
